#!/bin/sh

# See: https://gist.github.com/cobyism/4730490
# from: https://github.com/cobyism/dotfiles/blob/master/bin/git-gh-deploy

# Which lets you type commands like:
#
# git gh-deploy path/to/your/site


if [ -z "$1" ]
then
  echo "Which folder do you want to deploy to GitHub Pages?"
  exit 1
fi
git subtree push --prefix $1 origin gh-pages
